version: "2"
services:
  app:
    container_name: flask_app
    build: ./
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "4000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro